from inference_byt5 import Eng2KorTransliterator
from inference_arpabet_pipeline import Eng2KorTransliteratorPipeline
import time


pipeline = Eng2KorTransliteratorPipeline("./train/models/byt5-arpabet2kor")
TEST_CASES = [
    "strawberry",
    "philosophy",
    "rhythm",
    "schedule",
    "knight",
    "through",
    "psychology",
    "architecture",
    "queue",
    "island",
    "subtle",
    "honest",
    "castle",
    "answer",
    "whistle",
    "ghost",
    "ballet",
    "champagne",
    "croissant",
    "genre",
    "laser",
    "pixel",
    "tablet",
    "monitor",
    "battery",
    "camera",
    "guitar",
    "violin",
    "orchestra",
    "concert",
    "festival",
    "museum",
    "theater",
    "stadium",
    "library",
    "campus",
    "cafe",
    "bakery",
    "market",
    "pasta",
    "pizza",
    "mozzarella",
    "lasagna",
    "espresso",
    "latte",
    "sandwich",
    "omelette",
    "yogurt",
    "sausage",
    "airport",
    "station",
    "subway",
    "taxi",
    "highway",
    "tunnel",
    "elevator",
    "escalator",
    "balcony",
    "terrace",
    "university",
    "laboratory",
    "project",
    "algorithm",
    "variable",
    "function",
    "integer",
    "boolean",
    "package",
    "module",
    "concerthall",
    "smartphone",
    "notebook",
    "headphone",
    "backpack",
    "waterproof",
    "sunshine",
    "moonlight",
    "snowflake",
    "rainbow",
    "football",
    "basketball",
    "volleyball",
    "baseball",
    "handball",
    "workshop",
    "internship",
    "deadline",
    "checklist",
    "highlight",
    "makeup",
    "skincare",
    "perfume",
    "shampoo",
    "conditioner",
    "detergent",
    "toothpaste",
    "notebookPC",
    "powerbank",
    "earbuds",
    "wireless"
]

for case in TEST_CASES:
    start_time = time.time()
    result = pipeline.transliterate(case)
    end_time = time.time()
    print('original:{}'.format(case))
    print('transliterated:{}'.format(result))
    print(f"Time taken: {end_time - start_time} seconds")
    print("-"*100)
